### PR TITLE
Update with more photos, less text

### PR DESCRIPTION
**Pull request by gregdingle**
I tested locally and it looks good. 

What do we need to do to deploy @kuym ?

### CODE REVIEW

**Comment by kuym** [comment]
HI @gregdingle! Did you add the new image files to the commit? I don't see them in the PR

**Comment by gregdingle** [comment]
Right you are! Added now.

**Comment by gregdingle** [comment]
Could you give me write access? And tell me how to deploy?

**Comment by kuym** [comment]
Deploys occur automatically when the `gh-pages` branch is updated.  Magic!

**Pull request merged**
